version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - CORS_ORIGINS=${CORS_ORIGINS}
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/HoyoOCR
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    environment:
      - API_BASE_URL=${API_BASE_URL}
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge